env:
  commonjs: true
  es2021: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
extends:
  - airbnb-base
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
rules: {
  "prettier/prettier": [
      "error",
    {
      "singleQuote": true,
      "semi": false
    }
  ]
}
